---
- name: Enforce Password Complexity
  hosts: aws_region_us_east_1
  become: true

  tasks:

    - name: "Update Repository cache"
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true

    - name: Install pam-cracklib package
      apt:
        name: libpam-cracklib
        state: present

    - name: Configure PAM CrackLib Module for password strength requirements 
      lineinfile:
        path: /etc/pam.d/common-password
        regexp : '^password.*requisite.*pam_cracklib.so'
        line   : 'password requisite pam_cracklib.so retry=3 minlen=12 difok=3 ucredit=-1 lcredit=-2 dcredit=-1 ocredit=-1'
      
    - name : Ensure PAM Configuration is updated successfully and no syntax errors exists.
      shell : "put cli here"