---
 - hosts: aws_region_us_east_1
   gather_facts: no

   tasks:
    - name: Enable Root Login
      lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: '^PermitRootLogin'
            line: "PermitRootLogin no"
            state: present
            backup: yes
      become: yes

    - name: restart ssh
      become: yes
      ansible.builtin.service:
        name: sshd
        state: restarted