---
- name: Install HTTPD/ Apache
  hosts: aws_region_us_east_1
  become: true

  tasks:
    - name: Install a list of packages (suitable replacement for 2.11 loop deprecation warning)
      ansible.builtin.yum:
        name:
          - nginx
        state: present
      register: installation


    - name: List result
      debug:
        msg:  "{{ installation.results }}"

    - name: Start service nginx, if not started
      ansible.builtin.service:
        name: nginx
        state: started
      register: service_stat

    - name: List service status
      debug:
        msg:  "{{ service_stat.state }}"